export const DUMMY_TASKS = [
  {
    id: 't1',
    title: 'Complete Angular project',
    description: 'Finish the Angular project for the client by the end of the week.',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date('2023-10-15'),
    assignedTo: 'u1',
    createdBy: 'u2',
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2023-10-05'),
    comments: [
      {
        id: 'c1',
        text: 'Great job on the project so far!',
        createdBy: 'u3',
        createdAt: new Date('2023-10-02'),
        updatedAt: new Date('2023-10-03'),
      },
      {
        id: 'c2',
        text: 'I have some suggestions for improvement.',
        createdBy: 'u4',
        createdAt: new Date('2023-10-04'),
        updatedAt: new Date('2023-10-05'),
      },
    ],
  },
  {
    id: 't2',
    title: 'Prepare presentation slides',
    description: 'Create slides for the upcoming team meeting.',
    status: 'not-started',
    priority: 'medium',
    dueDate: new Date('2023-10-20'),
    assignedTo: 'u3',
    createdBy: 'u1',
    createdAt: new Date('2023-10-10'),
    updatedAt: new Date('2023-10-12'),
    comments: [],
  },
  {
    id: 't3',
    title: 'Fix login page bugs',
    description: 'Resolve issues reported on the login page by QA.',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date('2023-10-18'),
    assignedTo: 'u2',
    createdBy: 'u3',
    createdAt: new Date('2023-10-08'),
    updatedAt: new Date('2023-10-10'),
    comments: [
      {
        id: 'c3',
        text: 'The login button is not responsive on mobile.',
        createdBy: 'u4',
        createdAt: new Date('2023-10-09'),
        updatedAt: new Date('2023-10-09'),
      },
    ],
  },
  {
    id: 't4',
    title: 'Write unit tests for API',
    description: 'Add unit tests for the new API endpoints.',
    status: 'completed',
    priority: 'low',
    dueDate: new Date('2023-10-12'),
    assignedTo: 'u4',
    createdBy: 'u1',
    createdAt: new Date('2023-10-05'),
    updatedAt: new Date('2023-10-12'),
    comments: [
      {
        id: 'c4',
        text: 'Tests are passing successfully.',
        createdBy: 'u2',
        createdAt: new Date('2023-10-12'),
        updatedAt: new Date('2023-10-12'),
      },
    ],
  },
];